/* This file was automatically generated by CasADi 3.6.5+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) nmpc_func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s2[73] = {1, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s3[73] = {35, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s5[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s6[18] = {2, 5, 0, 2, 4, 6, 8, 10, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1};
static const casadi_int casadi_s7[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s8[86] = {10, 35, 0, 2, 4, 6, 8, 10, 12, 14, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 30, 31, 32, 33, 34, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 48, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5, 7, 6, 8, 7, 9, 8, 9, 0, 1, 0, 1, 0, 1, 2, 3, 2, 3, 2, 3, 4, 5, 4, 5, 4, 5, 6, 7, 6, 7, 6, 7, 8, 9, 8, 9, 8, 9};
static const casadi_int casadi_s9[22] = {18, 1, 0, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s10[60] = {18, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 10, 11, 12, 13, 14, 14, 15, 16, 17, 18, 18, 19, 20, 21, 22, 22, 0, 1, 0, 1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};
static const casadi_int casadi_s11[43] = {5, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s12[40] = {2, 35, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1};

/* J_v_func:(i0[10],i1[25],i2[10],i3[25])->(o0[1x35]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2;
  a0=arg[0]? arg[0][0] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0]? arg[0][1] : 0;
  a0=arg[2]? arg[2][1] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0]? arg[0][2] : 0;
  a2=arg[2]? arg[2][2] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[2]? arg[2][3] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[0]? arg[0][4] : 0;
  a0=arg[2]? arg[2][4] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[0]? arg[0][5] : 0;
  a2=arg[2]? arg[2][5] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0]? arg[0][6] : 0;
  a1=arg[2]? arg[2][6] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][6]=a2;
  a2=arg[0]? arg[0][7] : 0;
  a0=arg[2]? arg[2][7] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][7]=a1;
  a1=arg[0]? arg[0][8] : 0;
  a2=arg[2]? arg[2][8] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[0]? arg[0][9] : 0;
  a1=arg[2]? arg[2][9] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][9]=a2;
  a2=arg[1]? arg[1][0] : 0;
  a0=arg[3]? arg[3][0] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][10]=a1;
  a1=arg[1]? arg[1][1] : 0;
  a2=arg[3]? arg[3][1] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a1=arg[3]? arg[3][2] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][12]=a2;
  a2=arg[1]? arg[1][3] : 0;
  a0=arg[3]? arg[3][3] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][13]=a1;
  a1=arg[1]? arg[1][4] : 0;
  a2=arg[3]? arg[3][4] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a1=arg[3]? arg[3][5] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][15]=a2;
  a2=arg[1]? arg[1][6] : 0;
  a0=arg[3]? arg[3][6] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][16]=a1;
  a1=arg[1]? arg[1][7] : 0;
  a2=arg[3]? arg[3][7] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][17]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a1=arg[3]? arg[3][8] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][18]=a2;
  a2=arg[1]? arg[1][9] : 0;
  a0=arg[3]? arg[3][9] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][19]=a1;
  a1=arg[1]? arg[1][10] : 0;
  a2=arg[3]? arg[3][10] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][20]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a1=arg[3]? arg[3][11] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][21]=a2;
  a2=arg[1]? arg[1][12] : 0;
  a0=arg[3]? arg[3][12] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][22]=a1;
  a1=arg[1]? arg[1][13] : 0;
  a2=arg[3]? arg[3][13] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][23]=a0;
  a0=arg[1]? arg[1][14] : 0;
  a1=arg[3]? arg[3][14] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][24]=a2;
  a2=arg[1]? arg[1][15] : 0;
  a0=arg[3]? arg[3][15] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][25]=a1;
  a1=arg[1]? arg[1][16] : 0;
  a2=arg[3]? arg[3][16] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][26]=a0;
  a0=arg[1]? arg[1][17] : 0;
  a1=arg[3]? arg[3][17] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][27]=a2;
  a2=arg[1]? arg[1][18] : 0;
  a0=arg[3]? arg[3][18] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][28]=a1;
  a1=arg[1]? arg[1][19] : 0;
  a2=arg[3]? arg[3][19] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][29]=a0;
  a0=arg[1]? arg[1][20] : 0;
  a1=arg[3]? arg[3][20] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][30]=a2;
  a2=arg[1]? arg[1][21] : 0;
  a0=arg[3]? arg[3][21] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][31]=a1;
  a1=arg[1]? arg[1][22] : 0;
  a2=arg[3]? arg[3][22] : 0;
  a0=(a1*a2);
  a1=(a1*a2);
  a0=(a0+a1);
  if (res[0]!=0) res[0][32]=a0;
  a0=arg[1]? arg[1][23] : 0;
  a1=arg[3]? arg[3][23] : 0;
  a2=(a0*a1);
  a0=(a0*a1);
  a2=(a2+a0);
  if (res[0]!=0) res[0][33]=a2;
  a2=arg[1]? arg[1][24] : 0;
  a0=arg[3]? arg[3][24] : 0;
  a1=(a2*a0);
  a2=(a2*a0);
  a1=(a1+a2);
  if (res[0]!=0) res[0][34]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int J_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int J_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int J_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void J_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void J_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int J_v_func_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int J_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real J_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int J_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* J_vv_func:(i0[10],i1[25],i2[10],i3[25])->(o0[35x35,35nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][1] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][2] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][3] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][4] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0]? arg[0][6] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[0]? arg[0][7] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0]? arg[0][8] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[0]? arg[0][9] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][0] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][15]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][17]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][18]=a0;
  a0=arg[1]? arg[1][9] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][19]=a0;
  a0=arg[1]? arg[1][10] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][20]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][21]=a0;
  a0=arg[1]? arg[1][12] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][22]=a0;
  a0=arg[1]? arg[1][13] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][23]=a0;
  a0=arg[1]? arg[1][14] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][24]=a0;
  a0=arg[1]? arg[1][15] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][25]=a0;
  a0=arg[1]? arg[1][16] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][26]=a0;
  a0=arg[1]? arg[1][17] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][27]=a0;
  a0=arg[1]? arg[1][18] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][28]=a0;
  a0=arg[1]? arg[1][19] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][29]=a0;
  a0=arg[1]? arg[1][20] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][30]=a0;
  a0=arg[1]? arg[1][21] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][31]=a0;
  a0=arg[1]? arg[1][22] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][32]=a0;
  a0=arg[1]? arg[1][23] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][33]=a0;
  a0=arg[1]? arg[1][24] : 0;
  a0=(a0+a0);
  if (res[0]!=0) res[0][34]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_vv_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int J_vv_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int J_vv_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_vv_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int J_vv_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void J_vv_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void J_vv_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void J_vv_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int J_vv_func_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int J_vv_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real J_vv_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_vv_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* J_vv_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_vv_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* J_vv_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int J_vv_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int J_vv_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* ceq1_func:(i0[2],i1[10],i2[25],i3,i4,i5[2x5],i6[2x5],i7[2x5],i8[5])->(o0[10]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=arg[8]? arg[8][0] : 0;
  a4=arg[2]? arg[2][4] : 0;
  a4=(a3+a4);
  a5=(a2/a4);
  a6=arg[2]? arg[2][2] : 0;
  a7=(a1-a6);
  a5=(a5*a7);
  a5=(a1+a5);
  a7=(a2/a3);
  a8=(a2/a4);
  a7=(a7-a8);
  a8=arg[7]? arg[7][0] : 0;
  a9=arg[6]? arg[6][0] : 0;
  a10=(a8-a9);
  a7=(a7*a10);
  a5=(a5-a7);
  a7=arg[4]? arg[4][0] : 0;
  a10=(a4-a7);
  a10=(a10/a2);
  a10=exp(a10);
  a11=arg[0]? arg[0][0] : 0;
  a12=1.;
  a13=(a7/a3);
  a13=(a12-a13);
  a13=(a13*a6);
  a11=(a11-a13);
  a13=(a7/a3);
  a13=(a13*a1);
  a11=(a11-a13);
  a13=(a2/a4);
  a1=(a1-a6);
  a13=(a13*a1);
  a11=(a11-a13);
  a10=(a10*a11);
  a5=(a5+a10);
  a10=(a4-a7);
  a10=(a10/a2);
  a10=exp(a10);
  a11=(a3-a7);
  a11=(a11/a2);
  a11=exp(a11);
  a10=(a10-a11);
  a11=arg[5]? arg[5][0] : 0;
  a13=(a7/a3);
  a13=(a12-a13);
  a13=(a13*a9);
  a1=(a7/a3);
  a1=(a1*a8);
  a13=(a13+a1);
  a11=(a11-a13);
  a10=(a10*a11);
  a5=(a5+a10);
  a10=(a2/a4);
  a11=(a4-a7);
  a11=(a11/a2);
  a11=exp(a11);
  a10=(a10*a11);
  a11=(a2/a3);
  a13=(a3-a7);
  a13=(a13/a2);
  a13=exp(a13);
  a11=(a11*a13);
  a10=(a10-a11);
  a8=(a8-a9);
  a10=(a10*a8);
  a5=(a5-a10);
  a5=(a0-a5);
  if (res[0]!=0) res[0][0]=a5;
  a5=arg[1]? arg[1][1] : 0;
  a10=arg[2]? arg[2][1] : 0;
  a8=(a2/a4);
  a9=arg[2]? arg[2][3] : 0;
  a11=(a10-a9);
  a8=(a8*a11);
  a8=(a10+a8);
  a11=(a2/a3);
  a13=(a2/a4);
  a11=(a11-a13);
  a13=arg[7]? arg[7][1] : 0;
  a1=arg[6]? arg[6][1] : 0;
  a6=(a13-a1);
  a11=(a11*a6);
  a8=(a8-a11);
  a11=(a4-a7);
  a11=(a11/a2);
  a11=exp(a11);
  a6=arg[0]? arg[0][1] : 0;
  a14=(a7/a3);
  a14=(a12-a14);
  a14=(a14*a9);
  a6=(a6-a14);
  a14=(a7/a3);
  a14=(a14*a10);
  a6=(a6-a14);
  a14=(a2/a4);
  a10=(a10-a9);
  a14=(a14*a10);
  a6=(a6-a14);
  a11=(a11*a6);
  a8=(a8+a11);
  a11=(a4-a7);
  a11=(a11/a2);
  a11=exp(a11);
  a6=(a3-a7);
  a6=(a6/a2);
  a6=exp(a6);
  a11=(a11-a6);
  a6=arg[5]? arg[5][1] : 0;
  a14=(a7/a3);
  a12=(a12-a14);
  a12=(a12*a1);
  a14=(a7/a3);
  a14=(a14*a13);
  a12=(a12+a14);
  a6=(a6-a12);
  a11=(a11*a6);
  a8=(a8+a11);
  a11=(a2/a4);
  a4=(a4-a7);
  a4=(a4/a2);
  a4=exp(a4);
  a11=(a11*a4);
  a4=(a2/a3);
  a3=(a3-a7);
  a3=(a3/a2);
  a3=exp(a3);
  a4=(a4*a3);
  a11=(a11-a4);
  a13=(a13-a1);
  a11=(a11*a13);
  a8=(a8-a11);
  a8=(a5-a8);
  if (res[0]!=0) res[0][1]=a8;
  a8=arg[1]? arg[1][2] : 0;
  a11=arg[2]? arg[2][5] : 0;
  a13=arg[8]? arg[8][1] : 0;
  a1=arg[2]? arg[2][9] : 0;
  a1=(a13+a1);
  a4=(a2/a1);
  a3=arg[2]? arg[2][7] : 0;
  a7=(a11-a3);
  a4=(a4*a7);
  a4=(a11+a4);
  a7=(a2/a13);
  a6=(a2/a1);
  a7=(a7-a6);
  a6=arg[7]? arg[7][2] : 0;
  a12=arg[6]? arg[6][2] : 0;
  a14=(a6-a12);
  a7=(a7*a14);
  a4=(a4-a7);
  a7=(a1/a2);
  a7=exp(a7);
  a0=(a0-a3);
  a14=(a2/a1);
  a11=(a11-a3);
  a14=(a14*a11);
  a0=(a0-a14);
  a7=(a7*a0);
  a4=(a4+a7);
  a7=(a1/a2);
  a7=exp(a7);
  a0=(a13/a2);
  a0=exp(a0);
  a7=(a7-a0);
  a0=arg[5]? arg[5][2] : 0;
  a0=(a0-a12);
  a7=(a7*a0);
  a4=(a4+a7);
  a7=(a2/a1);
  a0=(a1/a2);
  a0=exp(a0);
  a7=(a7*a0);
  a0=(a2/a13);
  a14=(a13/a2);
  a14=exp(a14);
  a0=(a0*a14);
  a7=(a7-a0);
  a6=(a6-a12);
  a7=(a7*a6);
  a4=(a4-a7);
  a4=(a8-a4);
  if (res[0]!=0) res[0][2]=a4;
  a4=arg[1]? arg[1][3] : 0;
  a7=arg[2]? arg[2][6] : 0;
  a6=(a2/a1);
  a12=arg[2]? arg[2][8] : 0;
  a0=(a7-a12);
  a6=(a6*a0);
  a6=(a7+a6);
  a0=(a2/a13);
  a14=(a2/a1);
  a0=(a0-a14);
  a14=arg[7]? arg[7][3] : 0;
  a11=arg[6]? arg[6][3] : 0;
  a3=(a14-a11);
  a0=(a0*a3);
  a6=(a6-a0);
  a0=(a1/a2);
  a0=exp(a0);
  a5=(a5-a12);
  a3=(a2/a1);
  a7=(a7-a12);
  a3=(a3*a7);
  a5=(a5-a3);
  a0=(a0*a5);
  a6=(a6+a0);
  a0=(a1/a2);
  a0=exp(a0);
  a5=(a13/a2);
  a5=exp(a5);
  a0=(a0-a5);
  a5=arg[5]? arg[5][3] : 0;
  a5=(a5-a11);
  a0=(a0*a5);
  a6=(a6+a0);
  a0=(a2/a1);
  a1=(a1/a2);
  a1=exp(a1);
  a0=(a0*a1);
  a1=(a2/a13);
  a13=(a13/a2);
  a13=exp(a13);
  a1=(a1*a13);
  a0=(a0-a1);
  a14=(a14-a11);
  a0=(a0*a14);
  a6=(a6-a0);
  a6=(a4-a6);
  if (res[0]!=0) res[0][3]=a6;
  a6=arg[1]? arg[1][4] : 0;
  a0=arg[2]? arg[2][10] : 0;
  a14=arg[8]? arg[8][2] : 0;
  a11=arg[2]? arg[2][14] : 0;
  a11=(a14+a11);
  a1=(a2/a11);
  a13=arg[2]? arg[2][12] : 0;
  a5=(a0-a13);
  a1=(a1*a5);
  a1=(a0+a1);
  a5=(a2/a14);
  a3=(a2/a11);
  a5=(a5-a3);
  a3=arg[7]? arg[7][4] : 0;
  a7=arg[6]? arg[6][4] : 0;
  a12=(a3-a7);
  a5=(a5*a12);
  a1=(a1-a5);
  a5=(a11/a2);
  a5=exp(a5);
  a8=(a8-a13);
  a12=(a2/a11);
  a0=(a0-a13);
  a12=(a12*a0);
  a8=(a8-a12);
  a5=(a5*a8);
  a1=(a1+a5);
  a5=(a11/a2);
  a5=exp(a5);
  a8=(a14/a2);
  a8=exp(a8);
  a5=(a5-a8);
  a8=arg[5]? arg[5][4] : 0;
  a8=(a8-a7);
  a5=(a5*a8);
  a1=(a1+a5);
  a5=(a2/a11);
  a8=(a11/a2);
  a8=exp(a8);
  a5=(a5*a8);
  a8=(a2/a14);
  a12=(a14/a2);
  a12=exp(a12);
  a8=(a8*a12);
  a5=(a5-a8);
  a3=(a3-a7);
  a5=(a5*a3);
  a1=(a1-a5);
  a1=(a6-a1);
  if (res[0]!=0) res[0][4]=a1;
  a1=arg[1]? arg[1][5] : 0;
  a5=arg[2]? arg[2][11] : 0;
  a3=(a2/a11);
  a7=arg[2]? arg[2][13] : 0;
  a8=(a5-a7);
  a3=(a3*a8);
  a3=(a5+a3);
  a8=(a2/a14);
  a12=(a2/a11);
  a8=(a8-a12);
  a12=arg[7]? arg[7][5] : 0;
  a0=arg[6]? arg[6][5] : 0;
  a13=(a12-a0);
  a8=(a8*a13);
  a3=(a3-a8);
  a8=(a11/a2);
  a8=exp(a8);
  a4=(a4-a7);
  a13=(a2/a11);
  a5=(a5-a7);
  a13=(a13*a5);
  a4=(a4-a13);
  a8=(a8*a4);
  a3=(a3+a8);
  a8=(a11/a2);
  a8=exp(a8);
  a4=(a14/a2);
  a4=exp(a4);
  a8=(a8-a4);
  a4=arg[5]? arg[5][5] : 0;
  a4=(a4-a0);
  a8=(a8*a4);
  a3=(a3+a8);
  a8=(a2/a11);
  a11=(a11/a2);
  a11=exp(a11);
  a8=(a8*a11);
  a11=(a2/a14);
  a14=(a14/a2);
  a14=exp(a14);
  a11=(a11*a14);
  a8=(a8-a11);
  a12=(a12-a0);
  a8=(a8*a12);
  a3=(a3-a8);
  a3=(a1-a3);
  if (res[0]!=0) res[0][5]=a3;
  a3=arg[1]? arg[1][6] : 0;
  a8=arg[2]? arg[2][15] : 0;
  a12=arg[8]? arg[8][3] : 0;
  a0=arg[2]? arg[2][19] : 0;
  a0=(a12+a0);
  a11=(a2/a0);
  a14=arg[2]? arg[2][17] : 0;
  a4=(a8-a14);
  a11=(a11*a4);
  a11=(a8+a11);
  a4=(a2/a12);
  a13=(a2/a0);
  a4=(a4-a13);
  a13=arg[7]? arg[7][6] : 0;
  a5=arg[6]? arg[6][6] : 0;
  a7=(a13-a5);
  a4=(a4*a7);
  a11=(a11-a4);
  a4=(a0/a2);
  a4=exp(a4);
  a6=(a6-a14);
  a7=(a2/a0);
  a8=(a8-a14);
  a7=(a7*a8);
  a6=(a6-a7);
  a4=(a4*a6);
  a11=(a11+a4);
  a4=(a0/a2);
  a4=exp(a4);
  a6=(a12/a2);
  a6=exp(a6);
  a4=(a4-a6);
  a6=arg[5]? arg[5][6] : 0;
  a6=(a6-a5);
  a4=(a4*a6);
  a11=(a11+a4);
  a4=(a2/a0);
  a6=(a0/a2);
  a6=exp(a6);
  a4=(a4*a6);
  a6=(a2/a12);
  a7=(a12/a2);
  a7=exp(a7);
  a6=(a6*a7);
  a4=(a4-a6);
  a13=(a13-a5);
  a4=(a4*a13);
  a11=(a11-a4);
  a11=(a3-a11);
  if (res[0]!=0) res[0][6]=a11;
  a11=arg[1]? arg[1][7] : 0;
  a4=arg[2]? arg[2][16] : 0;
  a13=(a2/a0);
  a5=arg[2]? arg[2][18] : 0;
  a6=(a4-a5);
  a13=(a13*a6);
  a13=(a4+a13);
  a6=(a2/a12);
  a7=(a2/a0);
  a6=(a6-a7);
  a7=arg[7]? arg[7][7] : 0;
  a8=arg[6]? arg[6][7] : 0;
  a14=(a7-a8);
  a6=(a6*a14);
  a13=(a13-a6);
  a6=(a0/a2);
  a6=exp(a6);
  a1=(a1-a5);
  a14=(a2/a0);
  a4=(a4-a5);
  a14=(a14*a4);
  a1=(a1-a14);
  a6=(a6*a1);
  a13=(a13+a6);
  a6=(a0/a2);
  a6=exp(a6);
  a1=(a12/a2);
  a1=exp(a1);
  a6=(a6-a1);
  a1=arg[5]? arg[5][7] : 0;
  a1=(a1-a8);
  a6=(a6*a1);
  a13=(a13+a6);
  a6=(a2/a0);
  a0=(a0/a2);
  a0=exp(a0);
  a6=(a6*a0);
  a0=(a2/a12);
  a12=(a12/a2);
  a12=exp(a12);
  a0=(a0*a12);
  a6=(a6-a0);
  a7=(a7-a8);
  a6=(a6*a7);
  a13=(a13-a6);
  a13=(a11-a13);
  if (res[0]!=0) res[0][7]=a13;
  a13=arg[1]? arg[1][8] : 0;
  a6=arg[2]? arg[2][20] : 0;
  a7=arg[8]? arg[8][4] : 0;
  a8=arg[2]? arg[2][24] : 0;
  a8=(a7+a8);
  a0=(a2/a8);
  a12=arg[2]? arg[2][22] : 0;
  a1=(a6-a12);
  a0=(a0*a1);
  a0=(a6+a0);
  a1=(a2/a7);
  a14=(a2/a8);
  a1=(a1-a14);
  a14=arg[7]? arg[7][8] : 0;
  a4=arg[6]? arg[6][8] : 0;
  a5=(a14-a4);
  a1=(a1*a5);
  a0=(a0-a1);
  a1=(a8/a2);
  a1=exp(a1);
  a3=(a3-a12);
  a5=(a2/a8);
  a6=(a6-a12);
  a5=(a5*a6);
  a3=(a3-a5);
  a1=(a1*a3);
  a0=(a0+a1);
  a1=(a8/a2);
  a1=exp(a1);
  a3=(a7/a2);
  a3=exp(a3);
  a1=(a1-a3);
  a3=arg[5]? arg[5][8] : 0;
  a3=(a3-a4);
  a1=(a1*a3);
  a0=(a0+a1);
  a1=(a2/a8);
  a3=(a8/a2);
  a3=exp(a3);
  a1=(a1*a3);
  a3=(a2/a7);
  a5=(a7/a2);
  a5=exp(a5);
  a3=(a3*a5);
  a1=(a1-a3);
  a14=(a14-a4);
  a1=(a1*a14);
  a0=(a0-a1);
  a13=(a13-a0);
  if (res[0]!=0) res[0][8]=a13;
  a13=arg[1]? arg[1][9] : 0;
  a0=arg[2]? arg[2][21] : 0;
  a1=(a2/a8);
  a14=arg[2]? arg[2][23] : 0;
  a4=(a0-a14);
  a1=(a1*a4);
  a1=(a0+a1);
  a4=(a2/a7);
  a3=(a2/a8);
  a4=(a4-a3);
  a3=arg[7]? arg[7][9] : 0;
  a5=arg[6]? arg[6][9] : 0;
  a6=(a3-a5);
  a4=(a4*a6);
  a1=(a1-a4);
  a4=(a8/a2);
  a4=exp(a4);
  a11=(a11-a14);
  a6=(a2/a8);
  a0=(a0-a14);
  a6=(a6*a0);
  a11=(a11-a6);
  a4=(a4*a11);
  a1=(a1+a4);
  a4=(a8/a2);
  a4=exp(a4);
  a11=(a7/a2);
  a11=exp(a11);
  a4=(a4-a11);
  a11=arg[5]? arg[5][9] : 0;
  a11=(a11-a5);
  a4=(a4*a11);
  a1=(a1+a4);
  a4=(a2/a8);
  a8=(a8/a2);
  a8=exp(a8);
  a4=(a4*a8);
  a8=(a2/a7);
  a7=(a7/a2);
  a7=exp(a7);
  a8=(a8*a7);
  a4=(a4-a8);
  a3=(a3-a5);
  a4=(a4*a3);
  a1=(a1-a4);
  a13=(a13-a1);
  if (res[0]!=0) res[0][9]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ceq1_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ceq1_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ceq1_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void ceq1_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ceq1_func_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int ceq1_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ceq1_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s6;
    case 6: return casadi_s6;
    case 7: return casadi_s6;
    case 8: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ceq1_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* ceq1_v_func:(i0[2],i1[10],i2[25],i3,i4,i5[2x5],i6[2x5],i7[2x5],i8[5])->(o0[10x35,48nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a4, a5, a6, a7, a8, a9;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  a1=arg[8]? arg[8][1] : 0;
  a2=arg[2]? arg[2][9] : 0;
  a1=(a1+a2);
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1/a2);
  a3=exp(a3);
  a4=(-a3);
  if (res[0]!=0) res[0][1]=a4;
  if (res[0]!=0) res[0][2]=a0;
  a4=(a1/a2);
  a4=exp(a4);
  a5=(-a4);
  if (res[0]!=0) res[0][3]=a5;
  if (res[0]!=0) res[0][4]=a0;
  a5=arg[8]? arg[8][2] : 0;
  a6=arg[2]? arg[2][14] : 0;
  a5=(a5+a6);
  a6=(a5/a2);
  a6=exp(a6);
  a7=(-a6);
  if (res[0]!=0) res[0][5]=a7;
  if (res[0]!=0) res[0][6]=a0;
  a7=(a5/a2);
  a7=exp(a7);
  a8=(-a7);
  if (res[0]!=0) res[0][7]=a8;
  if (res[0]!=0) res[0][8]=a0;
  a8=arg[8]? arg[8][3] : 0;
  a9=arg[2]? arg[2][19] : 0;
  a8=(a8+a9);
  a9=(a8/a2);
  a9=exp(a9);
  a10=(-a9);
  if (res[0]!=0) res[0][9]=a10;
  if (res[0]!=0) res[0][10]=a0;
  a10=(a8/a2);
  a10=exp(a10);
  a11=(-a10);
  if (res[0]!=0) res[0][11]=a11;
  if (res[0]!=0) res[0][12]=a0;
  a11=arg[8]? arg[8][4] : 0;
  a12=arg[2]? arg[2][24] : 0;
  a11=(a11+a12);
  a12=(a11/a2);
  a12=exp(a12);
  a13=(-a12);
  if (res[0]!=0) res[0][13]=a13;
  if (res[0]!=0) res[0][14]=a0;
  a13=(a11/a2);
  a13=exp(a13);
  a14=(-a13);
  if (res[0]!=0) res[0][15]=a14;
  if (res[0]!=0) res[0][16]=a0;
  if (res[0]!=0) res[0][17]=a0;
  a14=arg[8]? arg[8][0] : 0;
  a15=arg[2]? arg[2][4] : 0;
  a15=(a14+a15);
  a16=(a2/a15);
  a17=arg[4]? arg[4][0] : 0;
  a18=(a15-a17);
  a18=(a18/a2);
  a18=exp(a18);
  a19=(a16*a18);
  a20=(a17/a14);
  a21=(a20*a18);
  a21=(a19+a21);
  a22=-1.;
  a21=(a21+a22);
  a23=(a2/a15);
  a21=(a21-a23);
  if (res[0]!=0) res[0][18]=a21;
  a21=(a2/a15);
  a24=(a15-a17);
  a24=(a24/a2);
  a24=exp(a24);
  a25=(a21*a24);
  a26=(a17/a14);
  a27=(a26*a24);
  a27=(a25+a27);
  a27=(a27+a22);
  a28=(a2/a15);
  a27=(a27-a28);
  if (res[0]!=0) res[0][19]=a27;
  a27=(a17/a14);
  a27=(a0-a27);
  a29=(a27*a18);
  a29=(a29-a19);
  a29=(a29+a23);
  if (res[0]!=0) res[0][20]=a29;
  a29=(a17/a14);
  a29=(a0-a29);
  a19=(a29*a24);
  a19=(a19-a25);
  a19=(a19+a28);
  if (res[0]!=0) res[0][21]=a19;
  a19=(a15-a17);
  a19=(a19/a2);
  a19=exp(a19);
  a25=(a2/a15);
  a30=arg[7]? arg[7][0] : 0;
  a31=arg[6]? arg[6][0] : 0;
  a32=(a30-a31);
  a33=(a25*a32);
  a33=(a19*a33);
  a33=(a33/a2);
  a25=(a25/a15);
  a19=(a19*a32);
  a25=(a25*a19);
  a33=(a33-a25);
  a25=(a15-a17);
  a25=(a25/a2);
  a25=exp(a25);
  a19=arg[5]? arg[5][0] : 0;
  a32=(a17/a14);
  a32=(a0-a32);
  a32=(a32*a31);
  a34=(a17/a14);
  a34=(a34*a30);
  a32=(a32+a34);
  a19=(a19-a32);
  a25=(a25*a19);
  a25=(a25/a2);
  a33=(a33-a25);
  a25=(a16/a15);
  a19=arg[2]? arg[2][0] : 0;
  a32=arg[2]? arg[2][2] : 0;
  a34=(a19-a32);
  a35=(a34*a18);
  a25=(a25*a35);
  a33=(a33-a25);
  a25=arg[0]? arg[0][0] : 0;
  a27=(a27*a32);
  a25=(a25-a27);
  a20=(a20*a19);
  a25=(a25-a20);
  a16=(a16*a34);
  a25=(a25-a16);
  a18=(a18*a25);
  a18=(a18/a2);
  a33=(a33-a18);
  a18=(a2/a15);
  a18=(a18/a15);
  a30=(a30-a31);
  a18=(a18*a30);
  a33=(a33+a18);
  a23=(a23/a15);
  a19=(a19-a32);
  a23=(a23*a19);
  a33=(a33+a23);
  if (res[0]!=0) res[0][22]=a33;
  a33=(a15-a17);
  a33=(a33/a2);
  a33=exp(a33);
  a23=(a2/a15);
  a19=arg[7]? arg[7][1] : 0;
  a32=arg[6]? arg[6][1] : 0;
  a18=(a19-a32);
  a30=(a23*a18);
  a30=(a33*a30);
  a30=(a30/a2);
  a23=(a23/a15);
  a33=(a33*a18);
  a23=(a23*a33);
  a30=(a30-a23);
  a23=(a15-a17);
  a23=(a23/a2);
  a23=exp(a23);
  a33=arg[5]? arg[5][1] : 0;
  a18=(a17/a14);
  a0=(a0-a18);
  a0=(a0*a32);
  a17=(a17/a14);
  a17=(a17*a19);
  a0=(a0+a17);
  a33=(a33-a0);
  a23=(a23*a33);
  a23=(a23/a2);
  a30=(a30-a23);
  a23=(a21/a15);
  a33=arg[2]? arg[2][1] : 0;
  a0=arg[2]? arg[2][3] : 0;
  a17=(a33-a0);
  a14=(a17*a24);
  a23=(a23*a14);
  a30=(a30-a23);
  a23=arg[0]? arg[0][1] : 0;
  a29=(a29*a0);
  a23=(a23-a29);
  a26=(a26*a33);
  a23=(a23-a26);
  a21=(a21*a17);
  a23=(a23-a21);
  a24=(a24*a23);
  a24=(a24/a2);
  a30=(a30-a24);
  a24=(a2/a15);
  a24=(a24/a15);
  a19=(a19-a32);
  a24=(a24*a19);
  a30=(a30+a24);
  a28=(a28/a15);
  a33=(a33-a0);
  a28=(a28*a33);
  a30=(a30+a28);
  if (res[0]!=0) res[0][23]=a30;
  a30=(a2/a1);
  a28=(a30*a3);
  a33=(a28+a22);
  a0=(a2/a1);
  a33=(a33-a0);
  if (res[0]!=0) res[0][24]=a33;
  a33=(a2/a1);
  a15=(a33*a4);
  a24=(a15+a22);
  a19=(a2/a1);
  a24=(a24-a19);
  if (res[0]!=0) res[0][25]=a24;
  a28=(a3-a28);
  a28=(a28+a0);
  if (res[0]!=0) res[0][26]=a28;
  a15=(a4-a15);
  a15=(a15+a19);
  if (res[0]!=0) res[0][27]=a15;
  a15=(a1/a2);
  a15=exp(a15);
  a28=(a2/a1);
  a24=arg[7]? arg[7][2] : 0;
  a32=arg[6]? arg[6][2] : 0;
  a23=(a24-a32);
  a21=(a28*a23);
  a21=(a15*a21);
  a21=(a21/a2);
  a28=(a28/a1);
  a15=(a15*a23);
  a28=(a28*a15);
  a21=(a21-a28);
  a28=(a1/a2);
  a28=exp(a28);
  a15=arg[5]? arg[5][2] : 0;
  a15=(a15-a32);
  a28=(a28*a15);
  a28=(a28/a2);
  a21=(a21-a28);
  a28=(a30/a1);
  a15=arg[2]? arg[2][5] : 0;
  a23=arg[2]? arg[2][7] : 0;
  a17=(a15-a23);
  a26=(a17*a3);
  a28=(a28*a26);
  a21=(a21-a28);
  a28=arg[1]? arg[1][0] : 0;
  a28=(a28-a23);
  a30=(a30*a17);
  a28=(a28-a30);
  a3=(a3*a28);
  a3=(a3/a2);
  a21=(a21-a3);
  a3=(a2/a1);
  a3=(a3/a1);
  a24=(a24-a32);
  a3=(a3*a24);
  a21=(a21+a3);
  a0=(a0/a1);
  a15=(a15-a23);
  a0=(a0*a15);
  a21=(a21+a0);
  if (res[0]!=0) res[0][28]=a21;
  a21=(a1/a2);
  a21=exp(a21);
  a0=(a2/a1);
  a15=arg[7]? arg[7][3] : 0;
  a23=arg[6]? arg[6][3] : 0;
  a3=(a15-a23);
  a24=(a0*a3);
  a24=(a21*a24);
  a24=(a24/a2);
  a0=(a0/a1);
  a21=(a21*a3);
  a0=(a0*a21);
  a24=(a24-a0);
  a0=(a1/a2);
  a0=exp(a0);
  a21=arg[5]? arg[5][3] : 0;
  a21=(a21-a23);
  a0=(a0*a21);
  a0=(a0/a2);
  a24=(a24-a0);
  a0=(a33/a1);
  a21=arg[2]? arg[2][6] : 0;
  a3=arg[2]? arg[2][8] : 0;
  a32=(a21-a3);
  a28=(a32*a4);
  a0=(a0*a28);
  a24=(a24-a0);
  a0=arg[1]? arg[1][1] : 0;
  a0=(a0-a3);
  a33=(a33*a32);
  a0=(a0-a33);
  a4=(a4*a0);
  a4=(a4/a2);
  a24=(a24-a4);
  a4=(a2/a1);
  a4=(a4/a1);
  a15=(a15-a23);
  a4=(a4*a15);
  a24=(a24+a4);
  a19=(a19/a1);
  a21=(a21-a3);
  a19=(a19*a21);
  a24=(a24+a19);
  if (res[0]!=0) res[0][29]=a24;
  a24=(a2/a5);
  a19=(a24*a6);
  a21=(a19+a22);
  a3=(a2/a5);
  a21=(a21-a3);
  if (res[0]!=0) res[0][30]=a21;
  a21=(a2/a5);
  a1=(a21*a7);
  a4=(a1+a22);
  a15=(a2/a5);
  a4=(a4-a15);
  if (res[0]!=0) res[0][31]=a4;
  a19=(a6-a19);
  a19=(a19+a3);
  if (res[0]!=0) res[0][32]=a19;
  a1=(a7-a1);
  a1=(a1+a15);
  if (res[0]!=0) res[0][33]=a1;
  a1=(a5/a2);
  a1=exp(a1);
  a19=(a2/a5);
  a4=arg[7]? arg[7][4] : 0;
  a23=arg[6]? arg[6][4] : 0;
  a0=(a4-a23);
  a33=(a19*a0);
  a33=(a1*a33);
  a33=(a33/a2);
  a19=(a19/a5);
  a1=(a1*a0);
  a19=(a19*a1);
  a33=(a33-a19);
  a19=(a5/a2);
  a19=exp(a19);
  a1=arg[5]? arg[5][4] : 0;
  a1=(a1-a23);
  a19=(a19*a1);
  a19=(a19/a2);
  a33=(a33-a19);
  a19=(a24/a5);
  a1=arg[2]? arg[2][10] : 0;
  a0=arg[2]? arg[2][12] : 0;
  a32=(a1-a0);
  a28=(a32*a6);
  a19=(a19*a28);
  a33=(a33-a19);
  a19=arg[1]? arg[1][2] : 0;
  a19=(a19-a0);
  a24=(a24*a32);
  a19=(a19-a24);
  a6=(a6*a19);
  a6=(a6/a2);
  a33=(a33-a6);
  a6=(a2/a5);
  a6=(a6/a5);
  a4=(a4-a23);
  a6=(a6*a4);
  a33=(a33+a6);
  a3=(a3/a5);
  a1=(a1-a0);
  a3=(a3*a1);
  a33=(a33+a3);
  if (res[0]!=0) res[0][34]=a33;
  a33=(a5/a2);
  a33=exp(a33);
  a3=(a2/a5);
  a1=arg[7]? arg[7][5] : 0;
  a0=arg[6]? arg[6][5] : 0;
  a6=(a1-a0);
  a4=(a3*a6);
  a4=(a33*a4);
  a4=(a4/a2);
  a3=(a3/a5);
  a33=(a33*a6);
  a3=(a3*a33);
  a4=(a4-a3);
  a3=(a5/a2);
  a3=exp(a3);
  a33=arg[5]? arg[5][5] : 0;
  a33=(a33-a0);
  a3=(a3*a33);
  a3=(a3/a2);
  a4=(a4-a3);
  a3=(a21/a5);
  a33=arg[2]? arg[2][11] : 0;
  a6=arg[2]? arg[2][13] : 0;
  a23=(a33-a6);
  a19=(a23*a7);
  a3=(a3*a19);
  a4=(a4-a3);
  a3=arg[1]? arg[1][3] : 0;
  a3=(a3-a6);
  a21=(a21*a23);
  a3=(a3-a21);
  a7=(a7*a3);
  a7=(a7/a2);
  a4=(a4-a7);
  a7=(a2/a5);
  a7=(a7/a5);
  a1=(a1-a0);
  a7=(a7*a1);
  a4=(a4+a7);
  a15=(a15/a5);
  a33=(a33-a6);
  a15=(a15*a33);
  a4=(a4+a15);
  if (res[0]!=0) res[0][35]=a4;
  a4=(a2/a8);
  a15=(a4*a9);
  a33=(a15+a22);
  a6=(a2/a8);
  a33=(a33-a6);
  if (res[0]!=0) res[0][36]=a33;
  a33=(a2/a8);
  a5=(a33*a10);
  a7=(a5+a22);
  a1=(a2/a8);
  a7=(a7-a1);
  if (res[0]!=0) res[0][37]=a7;
  a15=(a9-a15);
  a15=(a15+a6);
  if (res[0]!=0) res[0][38]=a15;
  a5=(a10-a5);
  a5=(a5+a1);
  if (res[0]!=0) res[0][39]=a5;
  a5=(a8/a2);
  a5=exp(a5);
  a15=(a2/a8);
  a7=arg[7]? arg[7][6] : 0;
  a0=arg[6]? arg[6][6] : 0;
  a3=(a7-a0);
  a21=(a15*a3);
  a21=(a5*a21);
  a21=(a21/a2);
  a15=(a15/a8);
  a5=(a5*a3);
  a15=(a15*a5);
  a21=(a21-a15);
  a15=(a8/a2);
  a15=exp(a15);
  a5=arg[5]? arg[5][6] : 0;
  a5=(a5-a0);
  a15=(a15*a5);
  a15=(a15/a2);
  a21=(a21-a15);
  a15=(a4/a8);
  a5=arg[2]? arg[2][15] : 0;
  a3=arg[2]? arg[2][17] : 0;
  a23=(a5-a3);
  a19=(a23*a9);
  a15=(a15*a19);
  a21=(a21-a15);
  a15=arg[1]? arg[1][4] : 0;
  a15=(a15-a3);
  a4=(a4*a23);
  a15=(a15-a4);
  a9=(a9*a15);
  a9=(a9/a2);
  a21=(a21-a9);
  a9=(a2/a8);
  a9=(a9/a8);
  a7=(a7-a0);
  a9=(a9*a7);
  a21=(a21+a9);
  a6=(a6/a8);
  a5=(a5-a3);
  a6=(a6*a5);
  a21=(a21+a6);
  if (res[0]!=0) res[0][40]=a21;
  a21=(a8/a2);
  a21=exp(a21);
  a6=(a2/a8);
  a5=arg[7]? arg[7][7] : 0;
  a3=arg[6]? arg[6][7] : 0;
  a9=(a5-a3);
  a7=(a6*a9);
  a7=(a21*a7);
  a7=(a7/a2);
  a6=(a6/a8);
  a21=(a21*a9);
  a6=(a6*a21);
  a7=(a7-a6);
  a6=(a8/a2);
  a6=exp(a6);
  a21=arg[5]? arg[5][7] : 0;
  a21=(a21-a3);
  a6=(a6*a21);
  a6=(a6/a2);
  a7=(a7-a6);
  a6=(a33/a8);
  a21=arg[2]? arg[2][16] : 0;
  a9=arg[2]? arg[2][18] : 0;
  a0=(a21-a9);
  a15=(a0*a10);
  a6=(a6*a15);
  a7=(a7-a6);
  a6=arg[1]? arg[1][5] : 0;
  a6=(a6-a9);
  a33=(a33*a0);
  a6=(a6-a33);
  a10=(a10*a6);
  a10=(a10/a2);
  a7=(a7-a10);
  a10=(a2/a8);
  a10=(a10/a8);
  a5=(a5-a3);
  a10=(a10*a5);
  a7=(a7+a10);
  a1=(a1/a8);
  a21=(a21-a9);
  a1=(a1*a21);
  a7=(a7+a1);
  if (res[0]!=0) res[0][41]=a7;
  a7=(a2/a11);
  a1=(a7*a12);
  a21=(a1+a22);
  a9=(a2/a11);
  a21=(a21-a9);
  if (res[0]!=0) res[0][42]=a21;
  a21=(a2/a11);
  a8=(a21*a13);
  a22=(a8+a22);
  a10=(a2/a11);
  a22=(a22-a10);
  if (res[0]!=0) res[0][43]=a22;
  a1=(a12-a1);
  a1=(a1+a9);
  if (res[0]!=0) res[0][44]=a1;
  a8=(a13-a8);
  a8=(a8+a10);
  if (res[0]!=0) res[0][45]=a8;
  a8=(a11/a2);
  a8=exp(a8);
  a1=(a2/a11);
  a22=arg[7]? arg[7][8] : 0;
  a5=arg[6]? arg[6][8] : 0;
  a3=(a22-a5);
  a6=(a1*a3);
  a6=(a8*a6);
  a6=(a6/a2);
  a1=(a1/a11);
  a8=(a8*a3);
  a1=(a1*a8);
  a6=(a6-a1);
  a1=(a11/a2);
  a1=exp(a1);
  a8=arg[5]? arg[5][8] : 0;
  a8=(a8-a5);
  a1=(a1*a8);
  a1=(a1/a2);
  a6=(a6-a1);
  a1=(a7/a11);
  a8=arg[2]? arg[2][20] : 0;
  a3=arg[2]? arg[2][22] : 0;
  a33=(a8-a3);
  a0=(a33*a12);
  a1=(a1*a0);
  a6=(a6-a1);
  a1=arg[1]? arg[1][6] : 0;
  a1=(a1-a3);
  a7=(a7*a33);
  a1=(a1-a7);
  a12=(a12*a1);
  a12=(a12/a2);
  a6=(a6-a12);
  a12=(a2/a11);
  a12=(a12/a11);
  a22=(a22-a5);
  a12=(a12*a22);
  a6=(a6+a12);
  a9=(a9/a11);
  a8=(a8-a3);
  a9=(a9*a8);
  a6=(a6+a9);
  if (res[0]!=0) res[0][46]=a6;
  a6=(a11/a2);
  a6=exp(a6);
  a9=(a2/a11);
  a8=arg[7]? arg[7][9] : 0;
  a3=arg[6]? arg[6][9] : 0;
  a12=(a8-a3);
  a22=(a9*a12);
  a22=(a6*a22);
  a22=(a22/a2);
  a9=(a9/a11);
  a6=(a6*a12);
  a9=(a9*a6);
  a22=(a22-a9);
  a9=(a11/a2);
  a9=exp(a9);
  a6=arg[5]? arg[5][9] : 0;
  a6=(a6-a3);
  a9=(a9*a6);
  a9=(a9/a2);
  a22=(a22-a9);
  a9=(a21/a11);
  a6=arg[2]? arg[2][21] : 0;
  a12=arg[2]? arg[2][23] : 0;
  a5=(a6-a12);
  a1=(a5*a13);
  a9=(a9*a1);
  a22=(a22-a9);
  a9=arg[1]? arg[1][7] : 0;
  a9=(a9-a12);
  a21=(a21*a5);
  a9=(a9-a21);
  a13=(a13*a9);
  a13=(a13/a2);
  a22=(a22-a13);
  a2=(a2/a11);
  a2=(a2/a11);
  a8=(a8-a3);
  a2=(a2*a8);
  a22=(a22+a2);
  a10=(a10/a11);
  a6=(a6-a12);
  a10=(a10*a6);
  a22=(a22+a10);
  if (res[0]!=0) res[0][47]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void ceq1_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ceq1_v_func_n_in(void) { return 9;}

CASADI_SYMBOL_EXPORT casadi_int ceq1_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ceq1_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    case 7: return "i7";
    case 8: return "i8";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ceq1_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s6;
    case 6: return casadi_s6;
    case 7: return casadi_s6;
    case 8: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ceq1_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ceq1_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq1_max_func:(i0[25],i1,i2,i3,i4,i5,i6[5])->(o0[18]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5;
  a0=1.;
  a1=arg[5]? arg[5][0] : 0;
  a2=arg[6]? arg[6][0] : 0;
  a3=arg[0]? arg[0][4] : 0;
  a2=(a2+a3);
  a3=(a1/a2);
  a3=(a0-a3);
  a4=arg[0]? arg[0][2] : 0;
  a3=(a3*a4);
  a4=(a1/a2);
  a5=arg[0]? arg[0][0] : 0;
  a4=(a4*a5);
  a3=(a3+a4);
  a4=arg[1]? arg[1][0] : 0;
  a3=(a3-a4);
  if (res[0]!=0) res[0][0]=a3;
  a3=(a1/a2);
  a0=(a0-a3);
  a3=arg[0]? arg[0][3] : 0;
  a0=(a0*a3);
  a1=(a1/a2);
  a2=arg[0]? arg[0][1] : 0;
  a1=(a1*a2);
  a0=(a0+a1);
  a1=arg[2]? arg[2][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a1=arg[3]? arg[3][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][6] : 0;
  a2=arg[4]? arg[4][0] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][7] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[0]? arg[0][8] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[0]? arg[0][10] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[0]? arg[0][11] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[0]? arg[0][12] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[0]? arg[0][13] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[0]? arg[0][15] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[0]? arg[0][16] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][11]=a0;
  a0=arg[0]? arg[0][17] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][12]=a0;
  a0=arg[0]? arg[0][18] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][13]=a0;
  a0=arg[0]? arg[0][20] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][14]=a0;
  a0=arg[0]? arg[0][21] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][15]=a0;
  a0=arg[0]? arg[0][22] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[0]? arg[0][23] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][17]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_max_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_max_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq1_max_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq1_max_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq1_max_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int cineq1_max_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq1_max_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_max_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_max_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_max_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s5;
    case 6: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_max_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq1_min_func:(i0[25],i1,i2,i3,i4,i5,i6[5])->(o0[18]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[1]? arg[1][0] : 0;
  a1=1.;
  a2=arg[5]? arg[5][0] : 0;
  a3=arg[6]? arg[6][0] : 0;
  a4=arg[0]? arg[0][4] : 0;
  a3=(a3+a4);
  a4=(a2/a3);
  a4=(a1-a4);
  a5=arg[0]? arg[0][2] : 0;
  a4=(a4*a5);
  a5=(a2/a3);
  a6=arg[0]? arg[0][0] : 0;
  a5=(a5*a6);
  a4=(a4+a5);
  a0=(a0-a4);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[2]? arg[2][0] : 0;
  a4=(a2/a3);
  a1=(a1-a4);
  a4=arg[0]? arg[0][3] : 0;
  a1=(a1*a4);
  a2=(a2/a3);
  a3=arg[0]? arg[0][1] : 0;
  a2=(a2*a3);
  a1=(a1+a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[0]? arg[0][5] : 0;
  a1=(a0-a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[4]? arg[4][0] : 0;
  a2=arg[0]? arg[0][6] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][3]=a2;
  a2=arg[0]? arg[0][7] : 0;
  a2=(a0-a2);
  if (res[0]!=0) res[0][4]=a2;
  a2=arg[0]? arg[0][8] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][5]=a2;
  a2=arg[0]? arg[0][10] : 0;
  a2=(a0-a2);
  if (res[0]!=0) res[0][6]=a2;
  a2=arg[0]? arg[0][11] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][7]=a2;
  a2=arg[0]? arg[0][12] : 0;
  a2=(a0-a2);
  if (res[0]!=0) res[0][8]=a2;
  a2=arg[0]? arg[0][13] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][9]=a2;
  a2=arg[0]? arg[0][15] : 0;
  a2=(a0-a2);
  if (res[0]!=0) res[0][10]=a2;
  a2=arg[0]? arg[0][16] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][11]=a2;
  a2=arg[0]? arg[0][17] : 0;
  a2=(a0-a2);
  if (res[0]!=0) res[0][12]=a2;
  a2=arg[0]? arg[0][18] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][13]=a2;
  a2=arg[0]? arg[0][20] : 0;
  a2=(a0-a2);
  if (res[0]!=0) res[0][14]=a2;
  a2=arg[0]? arg[0][21] : 0;
  a2=(a1-a2);
  if (res[0]!=0) res[0][15]=a2;
  a2=arg[0]? arg[0][22] : 0;
  a0=(a0-a2);
  if (res[0]!=0) res[0][16]=a0;
  a0=arg[0]? arg[0][23] : 0;
  a1=(a1-a0);
  if (res[0]!=0) res[0][17]=a1;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_min_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_min_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq1_min_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq1_min_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq1_min_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int cineq1_min_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq1_min_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_min_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_min_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_min_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s5;
    case 6: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_min_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq2_max_func:(i0[25],i1)->(o0[5]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][9] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][14] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[0]? arg[0][19] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[0]? arg[0][24] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_max_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f6(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq2_max_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_max_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq2_max_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq2_max_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq2_max_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq2_max_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq2_max_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq2_max_func_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int cineq2_max_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq2_max_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq2_max_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq2_max_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq2_max_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq2_max_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq2_max_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_max_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq2_min_func:(i0[25],i1[5])->(o0[5]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][4] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a1=arg[0]? arg[0][9] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a1=arg[0]? arg[0][14] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a1=arg[0]? arg[0][19] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a1=arg[0]? arg[0][24] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_min_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f7(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq2_min_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_min_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq2_min_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq2_min_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq2_min_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq2_min_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq2_min_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq2_min_func_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int cineq2_min_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq2_min_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq2_min_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq2_min_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq2_min_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq2_min_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq2_min_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_min_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq3_max_func:(i0[25],i1,i2,i3,i4[5])->(o0[2]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4;
  a0=arg[0]? arg[0][7] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a2=arg[4]? arg[4][0] : 0;
  a3=arg[3]? arg[3][0] : 0;
  a4=(a2-a3);
  a1=(a1*a4);
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][8] : 0;
  a1=arg[2]? arg[2][0] : 0;
  a2=(a2-a3);
  a1=(a1*a2);
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_max_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f8(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq3_max_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_max_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq3_max_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq3_max_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq3_max_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq3_max_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq3_max_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq3_max_func_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cineq3_max_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq3_max_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq3_max_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq3_max_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq3_max_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq3_max_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq3_max_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_max_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq3_min_func:(i0[25],i1,i2,i3,i4[5])->(o0[2]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[4]? arg[4][0] : 0;
  a2=arg[3]? arg[3][0] : 0;
  a3=(a1-a2);
  a0=(a0*a3);
  a3=arg[0]? arg[0][7] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[2]? arg[2][0] : 0;
  a1=(a1-a2);
  a0=(a0*a1);
  a1=arg[0]? arg[0][8] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_min_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f9(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq3_min_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_min_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq3_min_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq3_min_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq3_min_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq3_min_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq3_min_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq3_min_func_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cineq3_min_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq3_min_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq3_min_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq3_min_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq3_min_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq3_min_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq3_min_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_min_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq1_max_v_func:(i0[25],i1,i2,i3,i4,i5,i6[5])->(o0[18x35,22nz]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[5]? arg[5][0] : 0;
  a1=arg[6]? arg[6][0] : 0;
  a2=arg[0]? arg[0][4] : 0;
  a1=(a1+a2);
  a2=(a0/a1);
  if (res[0]!=0) res[0][0]=a2;
  a3=(a0/a1);
  if (res[0]!=0) res[0][1]=a3;
  a4=1.;
  a5=(a0/a1);
  a6=(a4-a5);
  if (res[0]!=0) res[0][2]=a6;
  a0=(a0/a1);
  a6=(a4-a0);
  if (res[0]!=0) res[0][3]=a6;
  a6=arg[0]? arg[0][2] : 0;
  a5=(a5/a1);
  a6=(a6*a5);
  a5=arg[0]? arg[0][0] : 0;
  a2=(a2/a1);
  a5=(a5*a2);
  a6=(a6-a5);
  if (res[0]!=0) res[0][4]=a6;
  a6=arg[0]? arg[0][3] : 0;
  a0=(a0/a1);
  a6=(a6*a0);
  a0=arg[0]? arg[0][1] : 0;
  a3=(a3/a1);
  a0=(a0*a3);
  a6=(a6-a0);
  if (res[0]!=0) res[0][5]=a6;
  if (res[0]!=0) res[0][6]=a4;
  if (res[0]!=0) res[0][7]=a4;
  if (res[0]!=0) res[0][8]=a4;
  if (res[0]!=0) res[0][9]=a4;
  if (res[0]!=0) res[0][10]=a4;
  if (res[0]!=0) res[0][11]=a4;
  if (res[0]!=0) res[0][12]=a4;
  if (res[0]!=0) res[0][13]=a4;
  if (res[0]!=0) res[0][14]=a4;
  if (res[0]!=0) res[0][15]=a4;
  if (res[0]!=0) res[0][16]=a4;
  if (res[0]!=0) res[0][17]=a4;
  if (res[0]!=0) res[0][18]=a4;
  if (res[0]!=0) res[0][19]=a4;
  if (res[0]!=0) res[0][20]=a4;
  if (res[0]!=0) res[0][21]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f10(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_max_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_max_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq1_max_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq1_max_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq1_max_v_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int cineq1_max_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq1_max_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_max_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_max_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_max_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s5;
    case 6: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_max_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_max_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq1_min_v_func:(i0[25],i1,i2,i3,i4,i5,i6[5])->(o0[18x35,22nz]) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[5]? arg[5][0] : 0;
  a1=arg[6]? arg[6][0] : 0;
  a2=arg[0]? arg[0][4] : 0;
  a1=(a1+a2);
  a2=(a0/a1);
  a3=(-a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=(a0/a1);
  a4=(-a3);
  if (res[0]!=0) res[0][1]=a4;
  a4=1.;
  a5=(a0/a1);
  a6=(a4-a5);
  a6=(-a6);
  if (res[0]!=0) res[0][2]=a6;
  a0=(a0/a1);
  a4=(a4-a0);
  a4=(-a4);
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[0]? arg[0][2] : 0;
  a5=(a5/a1);
  a4=(a4*a5);
  a5=arg[0]? arg[0][0] : 0;
  a2=(a2/a1);
  a5=(a5*a2);
  a4=(a4-a5);
  a4=(-a4);
  if (res[0]!=0) res[0][4]=a4;
  a4=arg[0]? arg[0][3] : 0;
  a0=(a0/a1);
  a4=(a4*a0);
  a0=arg[0]? arg[0][1] : 0;
  a3=(a3/a1);
  a0=(a0*a3);
  a4=(a4-a0);
  a4=(-a4);
  if (res[0]!=0) res[0][5]=a4;
  a4=-1.;
  if (res[0]!=0) res[0][6]=a4;
  if (res[0]!=0) res[0][7]=a4;
  if (res[0]!=0) res[0][8]=a4;
  if (res[0]!=0) res[0][9]=a4;
  if (res[0]!=0) res[0][10]=a4;
  if (res[0]!=0) res[0][11]=a4;
  if (res[0]!=0) res[0][12]=a4;
  if (res[0]!=0) res[0][13]=a4;
  if (res[0]!=0) res[0][14]=a4;
  if (res[0]!=0) res[0][15]=a4;
  if (res[0]!=0) res[0][16]=a4;
  if (res[0]!=0) res[0][17]=a4;
  if (res[0]!=0) res[0][18]=a4;
  if (res[0]!=0) res[0][19]=a4;
  if (res[0]!=0) res[0][20]=a4;
  if (res[0]!=0) res[0][21]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f11(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_min_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq1_min_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq1_min_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq1_min_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq1_min_v_func_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int cineq1_min_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq1_min_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_min_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq1_min_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_min_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s5;
    case 6: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq1_min_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq1_min_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq2_max_v_func:(i0[25],i1)->(o0[5x35,5nz]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_max_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f12(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq2_max_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_max_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq2_max_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq2_max_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq2_max_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq2_max_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq2_max_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq2_max_v_func_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int cineq2_max_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq2_max_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq2_max_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq2_max_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq2_max_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq2_max_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq2_max_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_max_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq2_min_v_func:(i0[25],i1[5])->(o0[5x35,5nz]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=-1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_min_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f13(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq2_min_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_min_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq2_min_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq2_min_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq2_min_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq2_min_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq2_min_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq2_min_v_func_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int cineq2_min_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq2_min_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq2_min_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq2_min_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq2_min_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq2_min_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq2_min_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq2_min_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq3_max_v_func:(i0[25],i1,i2,i3,i4[5])->(o0[2x35,2nz]) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_max_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f14(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq3_max_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_max_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq3_max_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq3_max_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq3_max_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq3_max_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq3_max_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq3_max_v_func_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cineq3_max_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq3_max_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq3_max_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq3_max_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq3_max_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq3_max_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq3_max_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_max_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}

/* cineq3_min_v_func:(i0[25],i1,i2,i3,i4[5])->(o0[2x35,2nz]) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=-1.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_min_v_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f15(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cineq3_min_v_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_min_v_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq3_min_v_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cineq3_min_v_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cineq3_min_v_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cineq3_min_v_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void cineq3_min_v_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cineq3_min_v_func_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int cineq3_min_v_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cineq3_min_v_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq3_min_v_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cineq3_min_v_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq3_min_v_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s5;
    case 2: return casadi_s5;
    case 3: return casadi_s5;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cineq3_min_v_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cineq3_min_v_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int cineq3_min_v_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
